name: Build React/Node App
on: push
jobs:
  lint:
    runs-on: ubuntu-slim
    steps:
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - name: Copy Codes
        uses: actions/checkout@v7
      - name: Install Node Modules
        run: npm ci
      - name: Lint App
        run: npm run lint

  test:
    runs-on: ubuntu-slim
    needs: lint
    steps:
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - name: Copy Codes
        uses: actions/checkout@v7
      - name: Install Node Modules
        run: npm ci
      - name: Test App
        run: npm run test

  deploy:
    runs-on: ubuntu-slim
    needs: test
    steps:
      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - name: Copy Codes
        uses: actions/checkout@v7
      - name: Install Node Modules
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Deploy App
        run: echo "Deploying..."
